### ISSUE TITLE
libFLEX 3.1.1 window appearing beneath other windows

### ISSUE THREAD

**Issue by Muirey03** [NSExceptional/FLEXing#11]
[Here is a video to demonstrate the issue.](https://streamable.com/df4hk) This issue occurs everywhere on SpringBoard, not just the widgets page.

Tested with an iPhone 8, iOS 13.2.2 and libFLEX v.3.1.1.

**Comment by ConorTheDev** [comment]
Also experiencing this issue, it's very annoying.

I'm also getting a grey overlay on all apps that aren't springboard occasionally. This issue went away when I removed FLEXing so it is an issue from it

**Comment by NSExceptional** [comment]
Fixed with 3.1.2, package submitted to BigBoss and the [releases tab](https://github.com/NSExceptional/FLEX/releases) over at NSExceptional/FLEX
