### ISSUE TITLE
Not displaying properly on the lock screen, iOS 13.3

### ISSUE THREAD

**Issue by ConorTheDev** [NSExceptional/FLEXing#12]
The classes view (the view inside the popup) doesn't display on iOS 13.3
It can be invoked, it can show the "View Hierarchy" title but the content doesn't show

This can be fixed with the a simple fix, adding this to the view controller:
```obj-c
- (BOOL)_canShowWhileLocked {
    return YES;
}
```

**Comment by ConorTheDev** [comment]
I couldn't find the correct class to put this in on my side, so I just added this hook to the ``Springboard.xm`` until an official fix is added.

```obj-c
%hook UIViewController
- (BOOL)_canShowWhileLocked {
    return YES;
}
%end
```

^ for anyone who's wondering

**Comment by NSExceptional** [comment]
Fixed with 3.1.2, package submitted to BigBoss. DEB available at the [releases tab](https://github.com/NSExceptional/FLEX/releases) over at NSExceptional/FLEX

**Comment by NSExceptional** [comment]
@ConorTheDev Is this fixed for you or nah?

**Comment by NSExceptional** [comment]
@ConorTheDev bump

**Comment by ConorTheDev** [comment]
Hi, yes this has been fixed
