### ISSUE TITLE
Touchscreen does not work in YandexTaxi application

### ISSUE THREAD

**Issue by alxr-s** [NSExceptional/FLEXing#13]
https://itunes.apple.com/ru/app/id472650686
The touchscreen does not respond to touch, after removing FLEXing everything returns to normal.
iphone 7 / ios 11.3

**Comment by sanecheks** [comment]
On FLEXing version 1.0.0 everything is fine

**Comment by sanecheks** [comment]
In icleaner pro the same thing(
Plz fix it
ios 11.3
Flexing 1.2.0

**Comment by NSExceptional** [comment]
Can you try this build?

[libflex_4.0.0-beta.deb.zip](https://github.com/Flipboard/FLEX/files/4131539/libflex_4.0.0-beta.deb.zip)

**Comment by sanecheks** [comment]
I tried the same thing.  In iCleaner, the touchscreen stops responding after a message about a new version of iCleaner itself

**Comment by r-plus** [comment]
I have same issue on Preference view (only that view) in PayPay application. 

Issue will only happen iOS 13 + iPhone 11 Pro (tested only unc0ver env)
Works well on iOS 12 + iPhone XS Max (chimera)

Sorry, PayPay app probably required japan sms auth to use, I’ll report when I found easily checkable app.

**Comment by r-plus** [comment]
only happen iOS 13, so I guess this issue is related iOS 13 new text editing three finger gesture...?

**Comment by NSExceptional** [comment]
FLEXing doesn't load FLEX into Snapchat on purpose, because Snapchat will ban you for it.

**Comment by NSExceptional** [comment]
It is working for me, are you on the latest version of iCleaner?

**Comment by sanecheks** [comment]
iCleaner 7.8.0 but as I wrote above the problem is not only in it.  libFLEX 3.1.2 FLEXing 1.0.0 no problem, with version 1.2.0 the above problem is present.

**Comment by NSExceptional** [comment]
I am using those versions and it works fine in iCleaner. Still debugging the taxi app though.

**Comment by sanecheks** [comment]
Please make it possible to downgrade FLEXing in cydia

**Comment by NSExceptional** [comment]
BigBoss does not support downgrades. In the future I will publish releases for older versions of libFLEX on my fork of FLEX.

**Comment by Art3mS1d** [comment]
Same with Mi Home. The app stops responding for touches after about 5 seconds from launch

**Comment by ngn999** [comment]
same problem in Starbucks China. after a pop sheet, it stops responding.
debugging with reveal.app, I found the is a UIWindow  on the top, and the app can not receive any touches.

**Comment by NSExceptional** [comment]
Is anyone still having this issue?
