### ISSUE TITLE
FLEX Not visible in some Apps

### ISSUE THREAD

**Issue by RPwnage** [NSExceptional/FLEXing#14]
Flex is not visible in some Apps. (e.g Instagram)

**Comment by NSExceptional** [comment]
iOS version, Instagram version, tweak versions plz

**Comment by RPwnage** [comment]
iOS 13.1.2, Instagram 126.0, Flexing 1.2.0

**Comment by RPwnage** [comment]
Another example would be snapchat

**Comment by NSExceptional** [comment]
FLEXing doesn't load FLEX into Snapchat on purpose, because Snapchat will ban you for it.

**Comment by NSExceptional** [comment]
It shows up for me in Instagram using all those same versions. How are you trying to make it appear?
