### ISSUE TITLE
FLEXing breaking battery view in checkra1n env.

### ISSUE THREAD

**Issue by r-plus** [NSExceptional/FLEXing#17]
## Issue
Battery graph view in Preference.app will not appear (consecutively showing loading spinner) when install FLEXing (not libFLEX) in checkra1n environment.

tested on iPhone X + iOS 13.3 + FLEXing 1.2.0

## How to fix
don't `%init();` for `powerlogHelperd` daemon process.

Related:
https://www.reddit.com/r/jailbreak/comments/dxd5kk/release_powerloghelperdfix_block_code_injection/

**Comment by NSExceptional** [comment]
This is not related to FLEX.

https://www.reddit.com/r/jailbreak/comments/evqfn4/discussion_tutorial_why_your_battery_screen_wont/

**Comment by r-plus** [comment]
ah, thanks link. I understood deeply.
