### ISSUE TITLE
FLEXing prevents NSLogs in Console.app

### ISSUE THREAD

**Issue by jontelang** [NSExceptional/FLEXing#18]
Not sure if this is intended behavior, of maybe just a bug?

I have some details here: https://www.reddit.com/r/jailbreakdevelopers/comments/fr5dzo/nslogs_on_ios_124/flttim7/?context=3

But in short, when FLEXing is installed I get no NSLogs in Console.app. Double checked by respringing looking for my logs _multiple times_ while installing/uninstalling FLEXing. 

I have iPhone X, 12.4. And I'm on Mojave 14.14.6

**Comment by jontelang** [comment]
https://github.com/Flipboard/FLEX/issues/397#issuecomment-604146418
https://github.com/Flipboard/FLEX/issues/402

**Comment by NSExceptional** [comment]
I will be fixing this in 4.1 (well, I will make it optional)

Just curious, do you not like to use the built in log viewer? Or is it not working either?

**Comment by jontelang** [comment]
The built in log viewer in FLEX, I would not use it unless it's a last resort (because I want to see the logs as I play around on my device in realtime). Seems like something you'd use if you forgot to run a beta version through xcode during development and just _have to_ see the logs, or if you do development only on your device because you have no macbook.

I actually built my own on-device viewer, and I didn't even use _that_ one. https://github.com/jontelang/syslogWindow

**Comment by NSExceptional** [comment]
Any particular reason you aren't using the debugger? Sounds like that would better suit your needs than waiting for log statements 😅

**Comment by jontelang** [comment]
Well as an example my current project has a lot of gesture recognizing going on so maintaining the touch while also juggling the debugger is just painful (I still use it, just when I really need it).
