### ISSUE TITLE
Cannot load Heap Objects on springboard and some apps.

### ISSUE THREAD

**Issue by thelazyitguy** [NSExceptional/FLEXing#21]
Loading heap objects only works in some apps, but never in the springboard. i'm running these versions.

Flexing - 1.2.0
libFLEX - 4.1.1-1

**Comment by NSExceptional** [comment]
iOS version and device

**Comment by thelazyitguy** [comment]
sorry,
iPhone 11 Pro Max
iOS 13.3

**Comment by thelazyitguy** [comment]
would you like a picture of what i get when i try to view heap objects on the springboard?

**Comment by NSExceptional** [comment]
Sure

**Comment by thelazyitguy** [comment]
![Uploading 80127733...]()

**Comment by thelazyitguy** [comment]
![heap](https://user-images.githubusercontent.com/60739640/80127996-18a5d880-8563-11ea-9373-2970c9817641.png)

**Comment by NSExceptional** [comment]
Fixed via [Flipboard/FLEX/pull/331](https://github.com/Flipboard/FLEX/pull/331)! Will be in the next release. Thanks to @opa334!
