### ISSUE TITLE
Status Bar in Apps

### ISSUE THREAD

**Issue by ifisq** [NSExceptional/FLEXing#23]
Hi,

I'm not sure if this is an issue that has been brought up in the past, but for some reason you cannot use FLEXing for the status bar in applications. Nothing from the status bar shows up in views section either while within an application. If you had any information as to why this might be happening, if it's a bug, or if you know of any way I can get around this, I'd really appreciate it. Thanks!

**Comment by NSExceptional** [comment]
The status bar is no longer part of the app in iOS 13. It is rendered from SpringBoard.
