### ISSUE TITLE
I don't understand. How to open it?

### ISSUE THREAD

**Issue by vadimszzz** [NSExceptional/FLEXing#34]
How do I get to this screen? 
Is it FLEXing on the screenshot or is it something else? I need the app that's on the ss.
I don't see an app on my springboard. How to open it? Long tap on the statusbar does nothing too.

![image](https://user-images.githubusercontent.com/88857748/132682779-3a58ff16-e0e5-4796-b3af-3c482c1039fb.png)

**Comment by vadimszzz** [comment]
I've installed FLEXible. Now long press works.

**Comment by NSExceptional** [comment]
FLEXible is outdated and not maintained by me. It won't even work on newer phones after the X.

Which phone do you have?

**Comment by vadimszzz** [comment]
> FLEXible is outdated and not maintained by me. It won't even work on newer phones after the X.
> 
> Which phone do you have?

Sorry didn't sent technical details.

iPhone 7 GSM; iOS 14.6; pm: Cydia; jb: checkra1n; downloaded FLEXing 1.3.1

**Comment by vadimszzz** [comment]
> FLEXible is outdated and not maintained by me. It won't even work on newer phones after the X.
> 
> Which phone do you have?

Your tool works, i tried again :)
