### ISSUE TITLE
only works on springboard

### ISSUE THREAD

**Issue by DetachHead** [NSExceptional/FLEXing#39]
i'm not sure how else to open FLEX but i do it by tapping and holding on the status bar. that works on the springboard but not inside any apps.

i'm on iOS 15.1.1 using dopamine. i tried installing @poomsmart's fork (#38) assuming that would fix it but it didn't.

**Comment by iCrazeiOS** [comment]
Hold the screen with three fingers

**Comment by DetachHead** [comment]
thanks! i couldn't find this method mentioned anywhere so i made a PR mentioning it in the readme #40

**Comment by NSExceptional** [comment]
Thank you @DetachHead!
