### ISSUE TITLE
Flex cant be opened in certain applications

### ISSUE THREAD

**Issue by Logxn** [NSExceptional/FLEXing#4]
In applications like Snapchat I can't open FLEX.
I assume its because its UI hides the statusbar

**Comment by NSExceptional** [comment]
Latest update adds a new gesture. Long press with 3 fingers anywhere.

**Comment by NSExceptional** [comment]
For the record I can open it in Snapchat just fine. Snapchat doesn't hide the status bar.

**Comment by Logxn** [comment]
There was no status bar for me when the login screen was showing

**Comment by NSExceptional** [comment]
Ah. Well, I added another gesture for you in the latest update.
