### ISSUE TITLE
Not working with NemID app

### ISSUE THREAD

**Issue by acecilia** [NSExceptional/FLEXing#5]
I am trying to use FLEXing with the NemID app: https://itunes.apple.com/dk/app/nemid-nøgleapp/id1300533299

I can not make it work with FLEXing, nether FLEXable. Is there any logs/debug tools I can use to troubleshoot it?

Jailbroken iOS 12.1.1, with Unc0ver.

Thanks!

**Comment by acecilia** [comment]
Update: after further testing, seems like FLEX appears behind the views of the app (setting the views of the app to `backgroundColor = .clear` allows you to see it), but because it is behind it is not receiving touches.

**Comment by acecilia** [comment]
Update: seems that the window level they are using is the highest, and that is why FLEX appears below it. Lowering it solves the problem:

```
[[UIApplication sharedApplication] keyWindow].windowLevel = UIWindowLevelNormal;
```

**Comment by NSExceptional** [comment]
Interesting! Maybe I should set the FLEX window height to the highest as well?

**Comment by acecilia** [comment]
@NSExceptional Sounds good!
