### ISSUE TITLE
Doesn't seem to work in any system apps

### ISSUE THREAD

**Issue by eskimo** [NSExceptional/FLEXing#6]
12.1.1b3 XS Max

The 3 finger method doesn't seem to work anywhere at all, and the status bar method works only in third party apps.

**Comment by NSExceptional** [comment]
It works in third party apps because they're likely running as arm64, while system apps are all running arm64e as you have a new device.

I'm gonna push a new release this weekend with a fix!

**Comment by eskimo** [comment]
Figured it had to do with that, but wanted to make sure :P

Thanks for the insanely fast response.
