### ISSUE TITLE
PAC crash on A12 devices

### ISSUE THREAD

**Issue by opa334** [NSExceptional/FLEXing#7]
Some features such as "Heap Objects" and "Live Instances" crash on A12 devices. The [crash log](https://pastebin.com/HTg47Tev) mentions a pointer authentication failure.

This gist should be useful: https://gist.github.com/summertriangle-dev/6b0449ce561f756ac82a4bc3de7af30a

Crash log is not symbolicated because the required tools have not been updated for arm64e.

**Comment by NSExceptional** [comment]
Hello, me again 😅

Can you try plugging your device into Xcode? Xcode can output symbolicated crash logs.

Open Xcode and press ⌘⇧2 and click "view device logs" then wait for everything to copy, close it and open it again

**Comment by opa334** [comment]
The crash log in there also doesn't seem to be symbolicated :/ https://pastebin.com/gKM7vAQW

Any black magic I have to apply here? :P

**Comment by NSExceptional** [comment]
Nope, it should take a couple seconds to symbolicate. Weird that it isn't symbolicating stuff UIKit and stuff at least…

**Comment by NSExceptional** [comment]
I will try to manually symbolicate the FLEXing parts

**Comment by opa334** [comment]
Had a quick look and if I can take a guess here, this probably causes the crash because context does not seem to be a signed pointer: https://github.com/Flipboard/FLEX/blob/1ef608cf8aa268716363586e894e053a3bed32c4/Classes/Utility/FLEXHeapEnumerator.m#L42

**Comment by NSExceptional** [comment]
Good catch! I'll look into that

**Comment by opa334** [comment]
Now that CrashReporter has been updated for arm64e, here is a symbolicated log: https://pastebin.com/iKVCZPVb

If I can find some time, I might try to fix this and submit a PR myself!

**Comment by NSExceptional** [comment]
Thanks! The repo for that is over at Flipboard/FLEX, not this repo, but you probably know that

**Comment by opa334** [comment]
I started to take a look and was able to get Heap Objects working again. With the latest commit of FLEX the PAC crash already seems to be gone, but the object list still seemed to be empty. I figured that [MAX_REALISTIC_ADDRESS](https://github.com/Flipboard/FLEX/blob/master/Classes/Utility/FLEXHeapEnumerator.m#L100) needs to be 64 bit on arm64e because the first 4 bytes are now being used by PAC. Alternatively, calling make_sym_readable from the [gist](https://gist.github.com/summertriangle-dev/6b0449ce561f756ac82a4bc3de7af30a) on lock_zone and unlock_zone also works.

Now there was a second issue too, actually calling (un)lock_zone seems to just lock the thread indefinitely on arm64e devices. After commenting out all calls to (un)lock_zone, it started to work again. I can't find any information on why these are called, but for some weird reason it doesn't seem to work on arm64e. I also tried to pac sign these pointers, but that made no difference as they seem to be pac signed already.

Also a small question: What would be the preferred place to put the stuff from the gist? Right now I just put the header into the project and included it. Is that fine or is there some general util header somewhere else already?

**Comment by NSExceptional** [comment]
As I understand it, the zone locks basically prevent (de)allocations from occurring on that heap. Which is what you want if you're going to enumerate it safely.

I hate this part of the codebase :( these APIs are so poorly documented

I'll look into it all again when I have some time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NSExceptional** [comment]
Hey! I'm gonna close this in hopes that your fix fixes this. If it doesn't, feel free to let me know and I'll reopen it. Your fix will be in the next release.

By the way, I'm hosting libFLEX on my own Cydia repo now, nscake.gitub.io. It will be removed from BigBoss soon.
