### ISSUE TITLE
Crash when tapping the "frame" property of a UIView

### ISSUE THREAD

**Issue by gilshahar7** [NSExceptional/FLEXing#8]
As title said, tapping the "frame" property of an UIView crashes the app/springboard.

Tried on an iPhone X and an A12 device both on ios 12.

**Comment by NSExceptional** [comment]
Fixed in an unreleased version of FLEX: https://github.com/Flipboard/FLEX/issues/287

Closing this for now. Keep an eye out for an update in the future.
