### ISSUE TITLE
Live instances always empty

### ISSUE THREAD

**Issue by gilshahar7** [NSExceptional/FLEXing#9]
Hi, my live instances list is always empty, even if i am in the "SpringBoard" base class. is this a known issue? it used to work fine not long ago.

**Comment by NSExceptional** [comment]
Known issue :/

**Comment by NSExceptional** [comment]
https://github.com/Flipboard/FLEX/issues/248

**Comment by gilshahar7** [comment]
Alright, thanks for the quick reply :) hope you find the culprit.
I didnt realize there was a different repository for Flex itself.

**Comment by NSExceptional** [comment]
Thanks! Me too. I want this feature to be reliable.

Yeah, this is just the jailbreak tweak wrapper haha. FLEX itself is a library used to debug apps even outside the jailbreak world

**Comment by NSExceptional** [comment]
I forgot to close this, but all issues related to this should be directed to https://github.com/Flipboard/FLEX/issues/248
